import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath, URL } from 'node:url';
import { argv } from 'node:process';
import { log } from 'node:console';
import { format } from 'prettier';

const root = new URL('../../', import.meta.url);
const read = (name) => readFile(new URL(`docs/assets/${name}`, root));
const output = new URL('apps/viewer/src/brand.generated.ts', root);
const source = await format(
  `// Generated by scripts/brand/sync.mjs from docs/assets. Do not edit.\n` +
    `export const LOGO_SVG = ${JSON.stringify((await read('logo.svg')).toString())};\n` +
    `export const ICON_SVG = ${JSON.stringify((await read('icon.svg')).toString())};\n` +
    `export const FAVICON_BASE64 = ${JSON.stringify((await read('favicon.ico')).toString('base64'))};\n`,
  { parser: 'typescript', singleQuote: true, printWidth: 92 },
);

if (argv.includes('--check')) {
  if ((await readFile(output, 'utf8')) !== source) {
    throw new Error('Brand assets are out of sync. Run node scripts/brand/sync.mjs');
  }
} else {
  await writeFile(output, source);
  log(`Updated ${fileURLToPath(output)}`);
}
