import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath, URL } from 'node:url';
import { argv } from 'node:process';
import { log } from 'node:console';
import { format } from 'prettier';

const root = new URL('../../', import.meta.url);
const read = (name) => readFile(new URL(`docs/assets/${name}`, root));

const HEADER = '// Generated by scripts/brand/sync.mjs from docs/assets. Do not edit.\n';
const svgExport = async (name, file) =>
  `export const ${name} = ${JSON.stringify((await read(file)).toString())};\n`;

const outputs = [
  {
    path: 'apps/viewer/src/brand.generated.ts',
    source: async () =>
      (await svgExport('LOGO_SVG', 'logo.svg')) +
      (await svgExport('LOGO_BLACK_SVG', 'logo-black.svg')) +
      (await svgExport('ICON_SVG', 'icon.svg')) +
      `export const FAVICON_BASE64 = ${JSON.stringify((await read('favicon.ico')).toString('base64'))};\n`,
  },
  {
    // The OAuth callback page serves from 127.0.0.1 and cannot reference
    // viewer assets; the icon mark is embedded here for the CLI instead.
    path: 'packages/theme/src/brand.generated.ts',
    source: async () => await svgExport('ICON_SVG', 'icon.svg'),
  },
];

for (const output of outputs) {
  const source = await format(HEADER + (await output.source()), {
    parser: 'typescript',
    singleQuote: true,
    printWidth: 92,
  });
  const target = new URL(output.path, root);
  if (argv.includes('--check')) {
    if ((await readFile(target, 'utf8')) !== source) {
      throw new Error(
        `Brand assets are out of sync: ${output.path}. Run node scripts/brand/sync.mjs`,
      );
    }
  } else {
    await writeFile(target, source);
    log(`Updated ${fileURLToPath(target)}`);
  }
}
