import { BASE_CSS, TOKENS_CSS } from '@mote/theme';

/**
 * Document CSS, inlined into every rendered document (baseline §29, §30):
 * a clean, reading-first page on the shared Mote tokens — 720px prose
 * column, 17px/1.75 body text, rule-free headings, softly framed tables,
 * accent-red used only for links, quotes and the brand mark. The slim
 * banner is sticky and blurred; dark mode comes from the token palette,
 * no JS.
 */
const DOCUMENT_CSS = `
::selection { background: var(--mote-accent); color: var(--mote-on-accent); }
.visually-hidden { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip-path: inset(50%); white-space: nowrap; border: 0; }

.mote-banner {
  position: sticky;
  top: 0;
  z-index: 10;
  border-bottom: 1px solid var(--mote-border);
  background: color-mix(in srgb, var(--mote-bg) 82%, transparent);
  backdrop-filter: saturate(1.5) blur(14px);
  -webkit-backdrop-filter: saturate(1.5) blur(14px);
}

.mote-banner-inner {
  max-width: 720px;
  margin: 0 auto;
  padding: 12px 20px;
  display: flex;
  align-items: center;
  gap: 14px;
}

.mote-brand {
  display: inline-flex;
  align-items: center;
  gap: 7px;
  flex-shrink: 0;
  font-size: 16px;
  font-weight: 700;
  letter-spacing: -0.02em;
  color: var(--mote-fg);
  text-decoration: none;
}

.mote-brand:hover { color: var(--mote-fg); text-decoration: none; }

.mote-brand-dot {
  width: 9px;
  height: 9px;
  border-radius: 3px;
  background: var(--mote-brand);
}

main {
  max-width: 720px;
  margin: 0 auto;
  padding: 3rem 20px 4rem;
}

/* ── Prose ─────────────────────────────────────────────────────────── */
article { font-size: 17px; line-height: 1.75; }

h1, h2, h3, h4, h5, h6 {
  margin: 1.8em 0 0.7em;
  line-height: 1.3;
  font-weight: 700;
  letter-spacing: -0.015em;
  scroll-margin-top: 76px;
}

h1 { font-size: 2em; margin-top: 0; }
h2 { font-size: 1.5em; margin-top: 2.2em; }
h3 { font-size: 1.22em; }
h4 { font-size: 1.05em; }
h5, h6 { font-size: 1em; color: var(--mote-muted); }

p, ul, ol, blockquote, table, pre { margin: 0 0 1.15em; }
ul, ol { padding-left: 1.5em; }
li { margin: 0.5em 0; }
li > ul, li > ol { margin-top: 0.35em; margin-bottom: 0; }
li > :last-child { margin-bottom: 0; }

article a {
  color: var(--mote-accent);
  text-decoration: none;
  border-bottom: 1px solid var(--mote-tint-border);
  transition: border-color 0.15s ease;
}
article a:hover { text-decoration: none; border-bottom-color: var(--mote-accent); }
/* Linked images (badges, logos): no underline under the picture. */
article a:has(img) { border-bottom: 0; }

code {
  background: var(--mote-code-bg);
  padding: 0.15em 0.4em;
  border-radius: 6px;
  font-size: 0.86em;
}

pre {
  background: var(--mote-pre-bg);
  border: 1px solid var(--mote-border);
  padding: 1rem 1.15rem;
  border-radius: 10px;
  overflow-x: auto;
  font-size: 0.87em;
  line-height: 1.6;
}

pre code {
  background: transparent;
  padding: 0;
  border-radius: 0;
  font-size: inherit;
}

/* Server-generated syntax tokens only; source HTML cannot supply classes. */
pre .hljs-comment, pre .hljs-quote { color: #6b7280; }
pre .hljs-keyword, pre .hljs-selector-tag, pre .hljs-literal, pre .hljs-doctag { color: #a6263c; }
pre .hljs-string, pre .hljs-regexp, pre .hljs-addition { color: #24633b; }
pre .hljs-number, pre .hljs-built_in, pre .hljs-type, pre .hljs-attr, pre .hljs-variable { color: #075985; }
pre .hljs-title, pre .hljs-section, pre .hljs-selector-class, pre .hljs-selector-id { color: #6f42c1; }
pre .hljs-name, pre .hljs-symbol, pre .hljs-bullet, pre .hljs-link { color: #9a4d00; }
pre .hljs-meta { color: #52647a; }
pre .hljs-deletion { color: #b42332; }
pre .hljs-emphasis { font-style: italic; }
pre .hljs-strong { font-weight: 700; }
@media (prefers-color-scheme: dark) {
  pre .hljs-comment, pre .hljs-quote { color: #9ca3af; }
  pre .hljs-keyword, pre .hljs-selector-tag, pre .hljs-literal, pre .hljs-doctag { color: #ff9caa; }
  pre .hljs-string, pre .hljs-regexp, pre .hljs-addition { color: #a5d6a7; }
  pre .hljs-number, pre .hljs-built_in, pre .hljs-type, pre .hljs-attr, pre .hljs-variable { color: #8ecbff; }
  pre .hljs-title, pre .hljs-section, pre .hljs-selector-class, pre .hljs-selector-id { color: #d2b4ff; }
  pre .hljs-name, pre .hljs-symbol, pre .hljs-bullet, pre .hljs-link { color: #ffc48c; }
  pre .hljs-meta { color: #adbbce; }
  pre .hljs-deletion { color: #ffa0a8; }
}

blockquote {
  margin-left: 0;
  padding: 0.1em 1.1em;
  color: #6b7280;
  border-left: 3px solid var(--mote-brand);
}
@media (prefers-color-scheme: dark) {
  blockquote { color: var(--mote-muted); }
}
blockquote > :first-child { margin-top: 0; }
blockquote > :last-child { margin-bottom: 0; }

/* Static GitHub-style alerts; titles and icons are generated by the parser. */
.markdown-alert {
  --alert-color: #0969da;
  margin: 0 0 1.15em;
  padding: 0.85em 1.1em;
  border-left: 3px solid var(--alert-color);
  border-radius: 0 8px 8px 0;
  background: color-mix(in srgb, var(--alert-color) 5%, var(--mote-bg));
  color: var(--mote-fg);
  overflow-wrap: anywhere;
}
.markdown-alert-tip { --alert-color: #1a7f37; }
.markdown-alert-important { --alert-color: #8250df; }
.markdown-alert-warning { --alert-color: #9a6700; }
.markdown-alert-caution { --alert-color: #cf222e; }
.markdown-alert > .markdown-alert-title {
  display: flex;
  align-items: center;
  gap: 0.5em;
  margin: 0 0 0.45em;
  color: var(--alert-color);
  font-weight: 600;
}
.markdown-alert-title svg { flex-shrink: 0; }
.markdown-alert > :last-child { margin-bottom: 0; }
@media (prefers-color-scheme: dark) {
  .markdown-alert { --alert-color: #79c0ff; }
  .markdown-alert-tip { --alert-color: #7ee787; }
  .markdown-alert-important { --alert-color: #d2a8ff; }
  .markdown-alert-warning { --alert-color: #e3b341; }
  .markdown-alert-caution { --alert-color: #ff7b72; }
}

/* Quiet table chrome. Raw HTML tables retain a compact scroll fallback;
   Markdown tables fill their separate scroll container below. */
table {
  display: block;
  width: max-content;
  max-width: 100%;
  overflow-x: auto;
  border-collapse: collapse;
  border: 1px solid var(--mote-border);
  border-radius: 8px;
  font-size: 0.95em;
  font-variant-numeric: tabular-nums;
}

th, td { padding: 12px 16px; text-align: left; vertical-align: top; }
/* Author CSS otherwise overrides the vetted HTML alignment hints. */
th[align="center"], td[align="center"] { text-align: center; }
th[align="right"], td[align="right"] { text-align: right; }
th { font-weight: 600; background: var(--mote-pre-bg); border-bottom: 1px solid var(--mote-border); }
td { border-bottom: 1px solid color-mix(in srgb, var(--mote-border) 65%, transparent); }
tr:last-child td { border-bottom: 0; }

/* Keep native table layout inside a keyboard-scrollable region. Short
   tables fill the column; wide tables keep readable cells and scroll. */
.table-scroll {
  max-width: 100%;
  overflow-x: auto;
  margin: 0 0 1.15em;
  border: 1px solid var(--mote-border);
  border-radius: 8px;
  scrollbar-width: thin;
  scrollbar-color: var(--mote-muted) var(--mote-pre-bg);
  /* Local covers hide the edge shadows at each scroll boundary. A short
     table covers both shadows, so it never suggests hidden columns. */
  background:
    linear-gradient(to right, var(--mote-bg) 40%, transparent) left / 32px 100% local no-repeat,
    linear-gradient(to left, var(--mote-bg) 40%, transparent) right / 32px 100% local no-repeat,
    linear-gradient(to right, color-mix(in srgb, var(--mote-fg) 14%, transparent), transparent) left / 12px 100% scroll no-repeat,
    linear-gradient(to left, color-mix(in srgb, var(--mote-fg) 14%, transparent), transparent) right / 12px 100% scroll no-repeat;
}
.table-scroll:focus-visible { outline: 2px solid var(--mote-accent); outline-offset: 3px; }
.table-scroll table {
  display: table;
  width: max-content;
  min-width: 100%;
  max-width: none;
  margin: 0;
  overflow: visible;
  border: 0;
  border-radius: 0;
}
.table-scroll th, .table-scroll td { min-width: 4em; max-width: 24em; overflow-wrap: anywhere; }

img { max-width: 100%; height: auto; box-sizing: border-box; border-radius: 8px; }

hr {
  height: 1px;
  border: 0;
  background: var(--mote-border);
  margin: 2.5em 0;
}

kbd {
  border: 1px solid var(--mote-border);
  border-bottom-width: 2px;
  border-radius: 6px;
  padding: 0.1em 0.4em;
  background: var(--mote-pre-bg);
  font-size: 0.85em;
}

mark { background: var(--mote-tint); color: inherit; padding: 0.05em 0.2em; border-radius: 4px; }

/* Static formulas and diagrams */
.math-inline { display: inline-block; max-width: 100%; overflow-x: auto; vertical-align: middle; }
.math-display { overflow-x: auto; margin: 1.4em 0; padding: 0.5em 0; }
.math-display math { min-width: max-content; }
.mermaid-diagram { margin: 0 0 1.4em; }
.mermaid-diagram figcaption { margin-bottom: 0.5em; color: var(--mote-muted); font-size: 0.85em; }
.diagram-scroll { overflow: auto; max-height: 640px; padding: 0.5em; border: 1px solid var(--mote-border); border-radius: 10px; }
.diagram-scroll svg {
  display: block; margin: auto; max-width: 100%; height: auto;
  --bg: var(--mote-bg); --fg: var(--mote-fg);
  --_text: var(--mote-fg); --_text-sec: var(--mote-muted);
  --_text-muted: var(--mote-muted); --_text-faint: var(--mote-muted);
  --_line: var(--mote-muted); --_arrow: var(--mote-fg);
  --_node-fill: var(--mote-pre-bg); --_node-stroke: var(--mote-border);
  --_group-fill: var(--mote-bg); --_group-hdr: var(--mote-pre-bg);
  --_inner-stroke: var(--mote-border); --_key-badge: var(--mote-pre-bg);
}
.diagram-scroll text, .diagram-scroll tspan { font-family: inherit; }
@media (max-width: 600px) { .diagram-scroll svg { max-width: none; } }
.diagram-scroll .mote-xychart-grid { fill: var(--mote-border); stroke: none; opacity: 0.65; }
.diagram-scroll .mote-xychart-label, .diagram-scroll .mote-xychart-axis-title { fill: var(--mote-muted); }
.diagram-scroll .mote-xychart-title { fill: var(--mote-fg); }
.diagram-scroll .mote-xychart-color-0 { --chart-color: var(--mote-accent); }
.diagram-scroll .mote-xychart-color-1 { --chart-color: #588ee6; }
.diagram-scroll .mote-xychart-color-2 { --chart-color: #399e70; }
.diagram-scroll .mote-xychart-color-3 { --chart-color: #a176ce; }
.diagram-scroll .mote-xychart-color-4 { --chart-color: #cb9038; }
.diagram-scroll .mote-xychart-color-5 { --chart-color: #36a0b0; }
.diagram-scroll .mote-xychart-color-6 { --chart-color: #c9759a; }
.diagram-scroll .mote-xychart-color-7 { --chart-color: var(--mote-muted); }
.diagram-scroll line[class*="mote-xychart-color-"] { stroke: var(--chart-color); }
.diagram-scroll .mote-xychart-bar { stroke: var(--chart-color); fill: color-mix(in srgb, var(--mote-bg) 75%, var(--chart-color)); stroke-width: 1.5; }
.diagram-scroll .mote-xychart-line, .diagram-scroll .mote-xychart-line-shadow { fill: none; stroke: var(--chart-color); stroke-width: 2.5; stroke-linecap: round; stroke-linejoin: round; }
.diagram-scroll .mote-xychart-line-shadow { stroke-width: 5; opacity: 0.12; }
.diagram-scroll .mote-xychart-dot { fill: var(--chart-color); stroke: var(--mote-bg); stroke-width: 2; }
.math-display:focus-visible, .diagram-scroll:focus-visible { outline: 2px solid var(--mote-accent); outline-offset: 3px; }
article .mermaid-diagram details { margin-top: 0.6em; font-size: 0.85em; }

/* Content <details> blocks */
article details {
  border: 1px solid var(--mote-border);
  border-radius: 10px;
  padding: 0.7em 1em;
  margin: 0 0 1.15em;
}
article summary { cursor: pointer; font-weight: 600; }
article summary:hover { color: var(--mote-accent); }
article details[open] > summary { margin-bottom: 0.6em; }

/* Static anchors work without JavaScript. Enhancement adds state, focus
   management and scroll position; it never changes the rendered article. */
.toc-trigger {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  margin-left: auto;
  min-width: 40px;
  min-height: 40px;
  box-sizing: border-box;
  padding: 8px 10px;
  font-size: 13px;
  border: 1px solid transparent;
  border-radius: 999px;
  color: var(--mote-muted);
  text-decoration: none;
}
.toc-trigger:hover { color: var(--mote-accent); background: var(--mote-tint); }
.toc-trigger[aria-expanded="true"] { color: var(--mote-fg); }

.toc-scrim {
  position: fixed;
  inset: 0;
  z-index: 38;
  background: rgb(15 17 21 / 0.32);
  opacity: 0;
  visibility: hidden;
  transition: opacity 0.18s ease, visibility 0.18s;
}
.toc-drawer {
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  z-index: 40;
  width: min(360px, 90vw);
  padding: 12px 16px 0;
  background: var(--mote-bg);
  border-left: 1px solid var(--mote-border);
  transform: translateX(105%);
  visibility: hidden;
  transition: transform 0.2s ease, visibility 0s 0.2s;
}
body:not([data-toc-enhanced]) .toc-drawer:target,
body[data-toc-open] .toc-drawer {
  transform: none;
  visibility: visible;
  box-shadow: -16px 0 48px rgb(15 17 21 / 0.1);
  transition: transform 0.2s ease, visibility 0s;
}
body:not([data-toc-enhanced]) .toc-drawer:target + .toc-scrim,
body[data-toc-open] .toc-scrim { opacity: 1; visibility: visible; }
body[data-toc-modal] { position: fixed; left: 0; right: 0; }

.toc-drawer-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-shrink: 0;
  min-height: 44px;
  padding: 4px 4px 12px;
  border-bottom: 1px solid var(--mote-border);
  margin-bottom: 8px;
}
.toc-title { font-size: 12px; font-weight: 600; color: var(--mote-muted); }
.toc-close {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 40px;
  min-height: 40px;
  border-radius: 6px;
  font-size: 20px;
  line-height: 1;
  color: var(--mote-muted);
  text-decoration: none;
}
.toc-close:hover { color: var(--mote-accent); background: var(--mote-tint); }
.toc-nav {
  min-height: 0;
  overflow-y: auto;
  overscroll-behavior: contain;
  scrollbar-width: thin;
  scrollbar-color: var(--mote-border) transparent;
  padding: 0 4px max(24px, env(safe-area-inset-bottom));
}
.toc-nav ul { list-style: none; margin: 0; padding: 0; }
.toc-nav li { margin: 2px 0; }
.toc-nav [hidden] { display: none !important; }
.toc-row { display: flex; align-items: flex-start; padding-left: calc(var(--toc-depth) * 16px); position: relative; }
.toc-row > a {
  display: block;
  flex: 1;
  min-width: 0;
  box-sizing: border-box;
  min-height: 36px;
  padding: 8px;
  border-radius: 5px;
  color: var(--mote-muted);
  font-size: 13px;
  line-height: 1.5;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  text-decoration: none;
}
.toc-row > a:only-child, .toc-toggle[hidden] + a { margin-left: 24px; }
.toc-nav > ul > li > .toc-row > a { color: var(--mote-fg); font-weight: 550; }
.toc-nav > ul > li > ul > li > .toc-row > a { font-weight: 500; }
.toc-row > a:hover { color: var(--mote-fg); background: var(--mote-pre-bg); }
.toc-row > a[aria-current] { color: var(--mote-accent); font-weight: 600; }
.toc-row:has(> a[aria-current])::before {
  content: ""; position: absolute; left: 0; top: 10px; bottom: 10px;
  width: 2px; min-height: 14px; border-radius: 2px; background: var(--mote-accent);
}
.toc-toggle {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex: 0 0 24px;
  min-height: 36px;
  border: 0;
  padding: 0;
  border-radius: 5px;
  color: var(--mote-muted);
  background: transparent;
  cursor: pointer;
}
.toc-toggle[aria-expanded="true"] svg { transform: rotate(90deg); }
.toc-toggle:hover { color: var(--mote-fg); background: var(--mote-pre-bg); }
.toc-toggle:focus-visible { outline: 2px solid var(--mote-accent); outline-offset: -2px; }
li[data-current-branch] > .toc-row > .toc-toggle[aria-expanded="false"] { color: var(--mote-accent); }

@media (min-width: 1100px) {
  .has-toc:not([data-toc-collapsed]) main,
  .has-toc:not([data-toc-collapsed]) .mote-colophon-inner { margin-left: calc((100% - 1052px) / 2); margin-right: 0; }
  .has-toc:not([data-toc-collapsed]) .mote-banner-inner { max-width: 1012px; }
  .toc-drawer {
    left: calc(50% + 266px);
    top: 88px;
    bottom: var(--toc-bottom, 32px);
    width: 260px;
    padding: 0;
    border: 0;
    background: transparent;
    transform: none;
    visibility: visible;
    z-index: 9;
    transition: none;
  }
  .toc-drawer-head { padding: 0 8px; border-bottom: 0; margin-bottom: 4px; }
  /* Native momentum scrolling can paint before the scroll handler runs.
     Keep the footer above the rail and links during that transient overlap. */
  .has-toc .mote-colophon { position: relative; z-index: 10; background: var(--mote-bg); }
  /* Center the 2px marker over the 1px rail at x = 1.5px. Keep both
     inside the scrollable area to avoid clipping their outer edges. */
  .toc-nav {
    padding-left: 0;
    background: linear-gradient(var(--mote-border), var(--mote-border)) 1px top / 1px 100% no-repeat;
  }
  .toc-row { padding-left: calc(5px + var(--toc-depth) * 16px); }
  .toc-row > a { min-height: 32px; padding-top: 6px; padding-bottom: 6px; }
  .toc-toggle { min-height: 32px; }
  .toc-row:has(> a[aria-current])::before { left: 0.5px; top: 8px; bottom: 8px; }
  body .toc-scrim { display: none; }
  body[data-toc-open] .toc-drawer, body:not([data-toc-enhanced]) .toc-drawer:target { box-shadow: none; }
  body[data-toc-collapsed] .toc-drawer { visibility: hidden; }
  body:not([data-toc-enhanced]) .toc-trigger, body:not([data-toc-enhanced]) .toc-close { display: none; }
}
@media (min-width: 1440px) {
  .has-toc:not([data-toc-collapsed]) main,
  .has-toc:not([data-toc-collapsed]) .mote-colophon-inner { margin-left: auto; margin-right: auto; }
  .has-toc:not([data-toc-collapsed]) .mote-banner-inner { max-width: 720px; }
  .toc-drawer { left: calc(50% + 412px); }
}
@media (min-width: 1600px) {
  .toc-drawer { width: 300px; }
}
@media (max-width: 767px) {
  .toc-drawer {
    top: auto; left: 0; right: 0; bottom: 0;
    width: 100%; height: min(80vh, 680px); height: min(80dvh, 680px);
    padding-top: 8px;
    border: 1px solid var(--mote-border); border-bottom: 0;
    border-radius: 18px 18px 0 0;
    transform: translateY(105%);
  }
  .toc-trigger, .toc-close, .toc-row > a, .toc-toggle { min-height: 44px; }
  .toc-trigger, .toc-close { min-width: 44px; }
  .toc-row > a { font-size: 14px; padding-top: 11px; padding-bottom: 11px; }
  .toc-toggle { flex-basis: 44px; }
  .toc-row > a:only-child, .toc-toggle[hidden] + a { margin-left: 44px; }
}

/* GFM task lists (markdown-it-task-lists): static disabled checkboxes. */
.task-list-item { list-style-type: none; }
.task-list-item .task-list-item-checkbox {
  margin: 0 0.45em 0.2em -1.4em;
  vertical-align: middle;
  accent-color: var(--mote-accent);
}

/* Footnotes (markdown-it-footnote). */
hr.footnotes-sep { display: none; }
.footnotes {
  border-top: 1px solid var(--mote-border);
  margin-top: 2.5em;
  padding-top: 1em;
  font-size: 0.88em;
  color: var(--mote-muted);
}
.footnotes ol { padding-left: 1.4em; }
a.footnote-ref, a.footnote-backref { border-bottom: 0; }

/* Colophon */
.mote-colophon { border-top: 1px solid var(--mote-border); }

.mote-colophon-inner {
  max-width: 720px;
  margin: 0 auto;
  padding: 22px 20px 34px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  font-size: 13px;
  color: var(--mote-muted);
}

.mote-colophon-mark {
  width: 10px;
  height: 10px;
  border-radius: 3px;
  background: var(--mote-brand);
}

.mote-colophon a {
  color: var(--mote-muted);
  text-decoration: none;
  border-bottom: 1px solid var(--mote-border);
}
.mote-colophon a:hover { color: var(--mote-accent); border-bottom-color: var(--mote-accent); }

@media (max-width: 600px) {
  main { padding-top: 30px; padding-bottom: 48px; }
  h1 { font-size: 1.7em; letter-spacing: 0; }
  h2 { font-size: 1.35em; margin-top: 40px; }
  h3 { font-size: 1.15em; }
  .mote-banner-inner { padding-top: 6px; padding-bottom: 6px; }
  th, td { padding: 10px 12px; }
}

@media print {
  .mote-banner { position: static; background: none; backdrop-filter: none; }
  .toc-trigger, .toc-scrim, .toc-drawer { display: none; }
  .has-toc:not([data-toc-collapsed]) main,
  .has-toc:not([data-toc-collapsed]) .mote-colophon-inner { margin: 0 auto; }
  body[data-toc-modal] { position: static; }
  .table-scroll { overflow: visible; background: none; border-radius: 0; }
  .table-scroll table { width: 100%; min-width: 0; table-layout: fixed; }
}

@media (prefers-reduced-motion: reduce) {
  .toc-drawer, .toc-scrim { transition: none; }
}
`;

export const PAGE_CSS = `${TOKENS_CSS}${BASE_CSS}${DOCUMENT_CSS}`;
