import { Buffer } from 'node:buffer';
import { execFile } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { execPath } from 'node:process';
import { promisify } from 'node:util';
import { sha256, targetFor } from './lib.mjs';
import { checkDocument, boundedFetch, documentId, fixtureMarker } from './smoke.mjs';
import { DeployError, requireThat } from './policy.mjs';

const execAsync = promisify(execFile);
export const fixturePng = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=',
  'base64',
);

// Called in a separate job, after installing the verified tarball without any
// credentials. Capture all CLI output: even a failure may contain a capability URL.
export async function publishSmoke({
  context,
  scratch,
  cliPath,
  serviceId,
  serviceSecret,
  processEnv,
  fetchImpl = globalThis.fetch,
  execImpl = execAsync,
}) {
  requireThat(Boolean(serviceId) && Boolean(serviceSecret), 'MISSING_SERVICE_CREDENTIALS');
  const origin = `https://${targetFor(context.environment).hostname}`;
  const marker = `${fixtureMarker} run ${context.runId}`;
  const document = join(scratch, 'smoke.md');
  await writeFile(join(scratch, 'pixel.png'), fixturePng);
  await writeFile(document, `# ${marker}\n\n![smoke](pixel.png)\n`);
  let result;
  try {
    const output = await execImpl(
      execPath,
      [cliPath, 'publish', document, '--api', origin, '--auth-mode', 'service', '--json'],
      {
        cwd: scratch,
        timeout: 120000,
        maxBuffer: 256 * 1024,
        env: {
          PATH: processEnv.PATH,
          HOME: scratch,
          XDG_CONFIG_HOME: scratch,
          TMPDIR: scratch,
          MOTE_AUTH_MODE: 'service',
          MOTE_SERVICE_API_URL: origin,
          MOTE_SERVICE_CLIENT_ID: serviceId,
          MOTE_SERVICE_CLIENT_SECRET: serviceSecret,
        },
      },
    );
    result = JSON.parse(output.stdout);
  } catch {
    throw new DeployError('WRITE_OUTCOME_UNKNOWN');
  }
  requireThat(
    documentId(result.id) && result.url === `${origin}/${result.id}`,
    'WRITE_INVALID_RESPONSE',
  );
  // Asset IDs are generated by the CLI, not hashes; discover only the expected
  // same-document image path in the returned public page, without logging it.
  const page = await boundedFetch(result.url, {}, fetchImpl);
  requireThat(page.status === 200 && page.text.includes(marker), 'WRITE_READBACK_FAILED');
  const matches = [
    ...page.text.matchAll(new RegExp(`/${result.id}/a/([1-9A-HJ-NP-Za-km-z]{12})`, 'g')),
  ];
  const assets = [...new Set(matches.map((match) => match[1]))];
  requireThat(assets.length === 1, 'WRITE_ASSET_READBACK_FAILED');
  await checkDocument(
    context.environment,
    { document: result.id, asset: assets[0], digest: sha256(fixturePng) },
    fetchImpl,
    marker,
  );
}
