import { describe, expect, it } from 'vitest';

import type { RandomSource } from '@mote/core';

import { allocateDocumentId, commitBundle, type PreparedBundle } from './publish.js';

/** Minimal R2Bucket stub recording put order and faking head() results. */
function stubBucket(options?: { existingKeys?: string[] }): {
  bucket: R2Bucket;
  puts: string[];
} {
  const puts: string[] = [];
  const existing = new Set(options?.existingKeys ?? []);
  const bucket = {
    async put(key: string): Promise<void> {
      puts.push(key);
      existing.add(key);
    },
    async head(key: string): Promise<{ key: string } | null> {
      return existing.has(key) ? { key } : null;
    },
  } as unknown as R2Bucket;
  return { bucket, puts };
}

const BUNDLE: PreparedBundle = {
  id: '7Vk3mQ9x2NFaP4Ls',
  entryName: 'README.md',
  markdownBytes: new TextEncoder().encode('# hi'),
  assets: [
    {
      id: 'Aq8K3pLm92Xq',
      references: ['./a.png'],
      contentType: 'image/png',
      bytes: new Uint8Array([1, 2, 3]),
      sha256: 'b'.repeat(64),
    },
    {
      id: 'X92LmNa81Pq2',
      references: ['./b.webp'],
      contentType: 'image/webp',
      bytes: new Uint8Array([4, 5, 6]),
      sha256: 'c'.repeat(64),
    },
  ],
};

describe('commitBundle — manifest last (§54)', () => {
  it('writes assets, then document.md, then manifest.json, in that order', async () => {
    const { bucket, puts } = stubBucket();
    await commitBundle(bucket, BUNDLE);

    expect(puts).toEqual([
      'documents/7Vk3mQ9x2NFaP4Ls/assets/Aq8K3pLm92Xq',
      'documents/7Vk3mQ9x2NFaP4Ls/assets/X92LmNa81Pq2',
      'documents/7Vk3mQ9x2NFaP4Ls/document.md',
      'documents/7Vk3mQ9x2NFaP4Ls/manifest.json',
    ]);
  });
});

describe('allocateDocumentId — collision retry (§5, §18)', () => {
  // Deterministic "random" source: fills the buffer with incrementing bytes
  // so each generated ID differs.
  function sequentialRandom(): RandomSource {
    let seed = 0;
    return (array) => {
      array.fill(seed++ % 200);
      return array;
    };
  }

  it('regenerates when the commit marker already exists', async () => {
    // Pre-seed the marker of the ID generated by seed byte 0.
    const firstRandom = sequentialRandom();
    const { bucket } = stubBucket();
    const firstId = await allocateDocumentId(bucket, firstRandom);

    const { bucket: colliding } = stubBucket({
      existingKeys: [`documents/${firstId}/manifest.json`],
    });
    const secondId = await allocateDocumentId(colliding, sequentialRandom());

    // seed 0's ID is taken (all-same-byte IDs are still valid Base58), so the
    // allocator must have moved on to a different ID.
    expect(secondId).not.toBe(firstId);
  });
});
